### ISSUE TITLE
Gnome 45 support

### ISSUE THREAD

**Issue by slimani-dev** [rahulhaque/php-laravel-valet-gnome-shell-extension#2]
it no longer supported on Ubuntu 23.10 in gnome 45

**Comment by rahulhaque** [comment]
Hi @moh-slimani I'll have a look in my free times.

**Comment by rahulhaque** [comment]
@moh-slimani can you please check if the [latest](https://github.com/rahulhaque/php-laravel-valet-gnome-shell-extension/releases/tag/v6.0) version is working for you?

**Comment by ramy7ajar** [comment]
> @moh-slimani can you please check if the [latest](https://github.com/rahulhaque/php-laravel-valet-gnome-shell-extension/releases/tag/v6.0) version is working for you?

![Screenshot from Screencast from 2023-12-26 08-42-38 webm](https://github.com/rahulhaque/php-laravel-valet-gnome-shell-extension/assets/154873592/0495b701-3001-4202-9e5d-5bbac1e2ed78)

Using Ubuntu 23, gnome shell v45.1

**Comment by rahulhaque** [comment]
@ramy7ajar thanks for informing. I have docker based environment and couldn't test it properly. I'll fix it soon.

**Comment by rahulhaque** [comment]
@ramy7ajar can you please test [v7.0](https://github.com/rahulhaque/php-laravel-valet-gnome-shell-extension/releases/tag/v7.0)?

**Comment by ramy7ajar** [comment]
Great, now it works without problems, thanks @rahulhaque 👍
